# ==============================================================================
# Development Cohort: SVM + XGBoost Stacking Model
# TRUE multiple imputation of BASIC laboratory variables + deterministic derivation
# Full development cohort (n = 1321)
#
# Purpose
# 1) Read the non-imputed, non-standardized development dataset.
# 2) Use the prespecified 16 FINAL model predictors and fixed SVM + XGBoost stacking architecture.
# 3) MICE imputes ONLY the 18 basic/source variables:
#       Sex, Smoke, Age, TP, ALB, CR, Fbg, PLT, TC, GGT, ALP,
#       NE_C, PT, HB, APTT, LDH, GLU, TG.
# 4) The six derived predictors are NEVER independently imputed:
#       AG_ratio = ALB / (TP - ALB)
#       eGFR     = CKD-EPI equation from CR, Age and Sex
#       PAR      = PLT / ALB
#       NPR      = NE_C / PLT
#       INR      = (PT / 13.1)^1.31
#       TyG      = log(1594.26 * TG * GLU / 2)
#    They are recalculated AFTER every completed MICE dataset is created.
# 5) Perform TRUE multiple imputation inside each CV split:
#       - each fold produces MICE_M completed BASIC-variable datasets;
#       - analysis rows fit each imputation model;
#       - assessment rows are ignore = TRUE and never estimate imputation rules;
#       - derived predictors are calculated separately within every completed dataset;
#       - each completed dataset is modeled separately;
#       - OOF probabilities are pooled across imputations by arithmetic mean.
# 6) Standardization + SMOTE + Tomek are performed inside the tidymodels recipe.
# 7) Tune SVM and XGBoost across all fold-imputation resamples using Bayesian optimization.
# 8) Generate pooled aligned OOF predictions and fit an Elastic Net meta-learner.
# 9) Fit Platt calibration on meta-learner OOF probabilities and determine a Youden threshold.
# 10) On the full development cohort, create MICE_M completed BASIC-variable datasets,
#     derive the six deterministic predictors, and refit one SVM and one XGBoost
#     model per imputation.
#
# IMPORTANT
# - The final 16 predictors and the SVM + XGBoost architecture are NOT re-selected here.
# - Derived predictors are NEVER passed to mice().
# - Outcome PDstage is NEVER used for imputation.
# - External validation data must NOT be used anywhere in this training script.
# - MICE_M = 5 is a practical first true-MI run; 10 or 20 can be used for sensitivity
#   analysis, but computational cost rises approximately linearly with MICE_M.
# ==============================================================================

rm(list = ls())
gc()

# Project-relative paths. Run this script from the repository root.
PROJECT_DIR <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
PRIVATE_DIR <- file.path(PROJECT_DIR, "private")
DATA_DIR <- file.path(PRIVATE_DIR, "data")
MODEL_DIR <- file.path(PRIVATE_DIR, "model_objects")
OUTPUT_ROOT <- file.path(PRIVATE_DIR, "analysis_outputs")
dir.create(DATA_DIR, showWarnings = FALSE, recursive = TRUE)
dir.create(MODEL_DIR, showWarnings = FALSE, recursive = TRUE)
dir.create(OUTPUT_ROOT, showWarnings = FALSE, recursive = TRUE)

# The private/ directory is intended for local use only and should not be
# committed to the public repository.

# ------------------------------------------------------------------------------
# 0. User settings
# ------------------------------------------------------------------------------
SEED <- 2025

# Put this script and the uploaded Excel file in the same working directory,
# or replace DATA_PATH with an absolute path.
DATA_PATH <- file.path(DATA_DIR, "development_data.xlsx")

# eGFR calculation settings.
# IMPORTANT: verify the Sex coding in the source data before running.
# This version assumes Sex = 0 is female and Sex = 1 is male.
SEX_FEMALE_CODE <- 0
SEX_MALE_CODE <- 1

# No race variable is present in the prespecified source-variable set.
# Therefore the race coefficient is fixed at 1.0 (non-Black coefficient).
EGFR_RACE_COEFFICIENT <- 1.0

if (identical(SEX_FEMALE_CODE, SEX_MALE_CODE)) {
  stop("SEX_FEMALE_CODE and SEX_MALE_CODE must be different.")
}
if (!is.finite(EGFR_RACE_COEFFICIENT) || EGFR_RACE_COEFFICIENT <= 0) {
  stop("EGFR_RACE_COEFFICIENT must be a positive finite number.")
}

# ------------------------------------------------------------------------------
# TRUE MULTIPLE IMPUTATION SETTINGS
# ------------------------------------------------------------------------------
# [1] Number of completed datasets generated by MICE.
#     The primary analysis uses m = 5. Larger values may be used for sensitivity analysis.
#     Computational cost increases approximately linearly with MICE_M.
MICE_M <- 5

# [2] Maximum number of iterations for each MICE chain.
#     The analysis uses 50 iterations.
MICE_MAXIT <- 50

# [3] Numerical tolerance used by mice::remove.lindep().
#     A small tolerance of 1e-8 is used.
MICE_EPS <- 1e-8

if (!is.finite(MICE_EPS) || MICE_EPS < 0) {
  stop("MICE_EPS must be a finite non-negative number.")
}

# [4] Imputation method for variables with missing values.
#     Predictive mean matching (PMM) is used.
MICE_METHOD <- "pmm"

# [5] Whether to print MICE iteration details to the console.
#     Set to TRUE only when iteration-level diagnostics are needed.
MICE_PRINT_FLAG <- FALSE

# [6] Number of outer cross-validation folds for SVM/XGBoost.
#     CV_FOLDS=5 and MICE_M=5 produce 25 fold-imputation resamples.
CV_FOLDS <- 5

# [7] Pooling rule for predictions across imputations.
#     Patient-level predicted probabilities are averaged across imputations.
#     The implemented rule is "mean_probability".
MI_POOLING_RULE <- "mean_probability"

# [8] Whether to export all completed full-cohort imputed datasets for local audit.
#     These exports contain patient-level information and must remain private.
EXPORT_ALL_MI_DATASETS <- TRUE

if (MICE_M < 1 || MICE_M != as.integer(MICE_M)) {
  stop("MICE_M must be a positive integer.")
}
if (MICE_M == 1) {
  warning("MICE_M = 1 is single imputation. Set MICE_M >= 2 for true multiple imputation.")
}
if (MI_POOLING_RULE != "mean_probability") {
  stop("This version currently implements MI_POOLING_RULE = 'mean_probability' only.")
}

OUTPUT_DIR <- file.path(OUTPUT_ROOT, "development_model")
dir.create(OUTPUT_DIR, showWarnings = FALSE, recursive = TRUE)

# Bayesian optimization settings used in the final analysis.
SVM_BAYES_INITIAL <- 30
SVM_BAYES_ITER <- 70

XGB_BAYES_INITIAL <- 50
XGB_BAYES_ITER <- 100

# ------------------------------------------------------------------------------
# PARALLEL SETTINGS
# ------------------------------------------------------------------------------
# tune >= 2.1.0 uses future/mirai rather than foreach/doParallel.
# NULL = automatically use physical_cores - 1.
PARALLEL_WORKERS <- 8L
TUNE_PARALLEL_OVER <- "resamples"

# ------------------------------------------------------------------------------
# 1. Package check and loading
# ------------------------------------------------------------------------------
required_pkgs <- c(
  "tidymodels", "themis", "mice", "readxl", "kernlab", "xgboost",
  "glmnet", "pROC", "openxlsx", "dplyr", "purrr", "tibble",
  "rsample", "future", "broom"
)

missing_pkgs <- required_pkgs[
  !vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_pkgs) > 0) {
  stop(
    paste0(
      "Missing packages: ", paste(missing_pkgs, collapse = ", "),
      "\nPlease install them first, e.g. install.packages(c(",
      paste(sprintf('"%s"', missing_pkgs), collapse = ", "), "))"
    )
  )
}

suppressPackageStartupMessages({
  library(tidymodels)
  library(themis)
  library(mice)
  library(readxl)
  library(kernlab)
  library(xgboost)
  library(glmnet)
  library(pROC)
  library(openxlsx)
  library(dplyr)
  library(purrr)
  library(tibble)
  library(rsample)
  library(future)
  library(broom)
})

tidymodels_prefer()

print_tune_notes_if_any <- function(x, label) {
  notes <- tryCatch(
    tune::collect_notes(x),
    error = function(e) NULL
  )
  if (!is.null(notes) && nrow(notes) > 0) {
    cat("\n---", label, "tuning notes ---\n")
    print(notes, n = Inf, width = Inf)
    cat("--- end tuning notes ---\n")
  }
  invisible(notes)
}

set.seed(SEED)

# ------------------------------------------------------------------------------
# 2. Prespecified model specification
# ------------------------------------------------------------------------------
binary_vars <- c("Sex", "Smoke")

# Final 16 model predictors.
continuous_vars <- c(
  "Age", "AG_ratio", "eGFR", "Fbg", "PAR", "TC", "GGT", "ALP",
  "NPR", "INR", "HB", "APTT", "LDH", "TyG"
)

predictor_vars <- c(binary_vars, continuous_vars)
outcome_var <- "PDstage"

stopifnot(length(predictor_vars) == 16)

# Six deterministic/derived final predictors. These are NEVER imputed by MICE.
derived_vars <- c("AG_ratio", "eGFR", "PAR", "NPR", "INR", "TyG")

# MICE receives ONLY these 18 basic/source variables.
# Derived variables are calculated after each completed imputation.
imputation_vars <- c(
  "Sex", "Smoke", "Age", "TP", "ALB", "CR", "Fbg", "PLT", "TC",
  "GGT", "ALP", "NE_C", "PT", "HB", "APTT", "LDH", "GLU", "TG"
)

stopifnot(length(imputation_vars) == 18)
stopifnot(length(intersect(derived_vars, imputation_vars)) == 0)

# ------------------------------------------------------------------------------
# 3. Helper functions
# ------------------------------------------------------------------------------

# 3.1 Convert outcome to a factor with severe periodontitis as the FIRST/event
#     level. This avoids event-level inconsistencies between different scripts.
to_stage_factor <- function(x) {
  x_chr <- trimws(tolower(as.character(x)))

  out <- dplyr::case_when(
    x_chr %in% c("stage1", "1") ~ "Stage1",
    x_chr %in% c("stage0", "0") ~ "Stage0",
    TRUE ~ NA_character_
  )

  if (anyNA(out)) {
    stop("PDstage contains missing or unrecognized values.")
  }

  factor(
    out,
    levels = c("Stage1", "Stage0")
  )
}

# 3.2 Deterministically derive the six non-imputed predictors from BASIC variables.
#
# Derived-predictor formulas:
#   AG_ratio = ALB / (TP - ALB)
#   INR      = (PT / 13.1)^1.31
#   NPR      = NE_C / PLT
#   PAR      = PLT / ALB
#   TyG      = ln(1594.26 * TG * GLU / 2)
#
# eGFR:
#   Scr_mg_dL = CR / 88.4
#   eGFR = 141 * min(Scr/kappa, 1)^alpha * max(Scr/kappa, 1)^(-1.209) *
#          0.993^Age * sex_coefficient * race_coefficient
#   female: kappa=0.7, alpha=-0.329, sex coefficient=1.018
#   male:   kappa=0.9, alpha=-0.411, sex coefficient=1
#
# strict = FALSE is used only for the raw pre-imputation audit, where missing
# source values are expected. strict = TRUE is used after MICE completion.
derive_model_predictors <- function(
    df,
    strict = TRUE,
    female_code = SEX_FEMALE_CODE,
    male_code = SEX_MALE_CODE,
    race_coefficient = EGFR_RACE_COEFFICIENT
) {
  required_basic <- imputation_vars
  missing_basic <- setdiff(required_basic, names(df))

  if (length(missing_basic) > 0) {
    stop(
      paste0(
        "Cannot derive model predictors. Missing BASIC columns: ",
        paste(missing_basic, collapse = ", ")
      )
    )
  }

  out <- as_tibble(df)

  out <- out |>
    mutate(
      across(
        all_of(required_basic),
        ~ suppressWarnings(as.numeric(.x))
      )
    )

  # Sex coding is required for the user-specified eGFR equation.
  sex_nonmissing <- out$Sex[!is.na(out$Sex)]
  if (length(sex_nonmissing) > 0 &&
      !all(sex_nonmissing %in% c(female_code, male_code))) {
    stop(
      paste0(
        "Sex contains values outside the configured codes ",
        female_code, " (female) and ", male_code, " (male)."
      )
    )
  }

  n <- nrow(out)

  scr_mg_dl <- out$CR / 88.4
  is_female <- out$Sex == female_code
  is_male <- out$Sex == male_code

  kappa <- ifelse(is_female, 0.7, ifelse(is_male, 0.9, NA_real_))
  alpha <- ifelse(is_female, -0.329, ifelse(is_male, -0.411, NA_real_))
  sex_coefficient <- ifelse(is_female, 1.018, ifelse(is_male, 1.0, NA_real_))

  # Initialize derived vectors so invalid raw/pre-imputation combinations become NA
  # without generating divide-by-zero / log warnings.
  AG_ratio_calc <- rep(NA_real_, n)
  eGFR_calc <- rep(NA_real_, n)
  PAR_calc <- rep(NA_real_, n)
  NPR_calc <- rep(NA_real_, n)
  INR_calc <- rep(NA_real_, n)
  TyG_calc <- rep(NA_real_, n)

  ag_denom <- out$TP - out$ALB
  idx_ag <- !is.na(out$ALB) & !is.na(ag_denom) & ag_denom > 0
  AG_ratio_calc[idx_ag] <- out$ALB[idx_ag] / ag_denom[idx_ag]

  idx_egfr <- (
    !is.na(scr_mg_dl) & scr_mg_dl > 0 &
      !is.na(out$Age) & out$Age >= 0 &
      !is.na(kappa) & !is.na(alpha) & !is.na(sex_coefficient)
  )
  if (any(idx_egfr)) {
    scr_ratio_valid <- scr_mg_dl[idx_egfr] / kappa[idx_egfr]
    eGFR_calc[idx_egfr] <-
      141 *
      pmin(scr_ratio_valid, 1)^alpha[idx_egfr] *
      pmax(scr_ratio_valid, 1)^(-1.209) *
      0.993^out$Age[idx_egfr] *
      sex_coefficient[idx_egfr] *
      race_coefficient
  }

  idx_par <- !is.na(out$PLT) & !is.na(out$ALB) & out$ALB > 0
  PAR_calc[idx_par] <- out$PLT[idx_par] / out$ALB[idx_par]

  idx_npr <- !is.na(out$NE_C) & !is.na(out$PLT) & out$PLT > 0
  NPR_calc[idx_npr] <- out$NE_C[idx_npr] / out$PLT[idx_npr]

  idx_inr <- !is.na(out$PT) & out$PT > 0
  INR_calc[idx_inr] <- (out$PT[idx_inr] / 13.1)^1.31

  tyg_arg <- 1594.26 * out$TG * out$GLU / 2
  idx_tyg <- !is.na(tyg_arg) & tyg_arg > 0
  TyG_calc[idx_tyg] <- log(tyg_arg[idx_tyg])

  derived <- tibble(
    Sex = out$Sex,
    Smoke = out$Smoke,
    Age = out$Age,
    AG_ratio = AG_ratio_calc,
    eGFR = eGFR_calc,
    Fbg = out$Fbg,
    PAR = PAR_calc,
    TC = out$TC,
    GGT = out$GGT,
    ALP = out$ALP,
    NPR = NPR_calc,
    INR = INR_calc,
    HB = out$HB,
    APTT = out$APTT,
    LDH = out$LDH,
    TyG = TyG_calc
  ) |>
    select(all_of(predictor_vars))

  if (strict && anyNA(derived)) {
    bad_cols <- names(derived)[vapply(derived, anyNA, logical(1))]
    stop(
      paste0(
        "Derived model predictors contain missing/invalid values after MICE: ",
        paste(bad_cols, collapse = ", "),
        ". Check source values (especially TP>ALB, CR>0, ALB>0, PLT>0, ",
        "PT>0, TG>0, GLU>0) and Sex coding."
      )
    )
  }

  if (strict) {
    nonfinite_cols <- names(derived)[
      vapply(
        derived,
        function(x) any(!is.finite(as.numeric(x))),
        logical(1)
      )
    ]

    if (length(nonfinite_cols) > 0) {
      stop(
        paste0(
          "Non-finite derived/model values found after MICE: ",
          paste(nonfinite_cols, collapse = ", ")
        )
      )
    }
  }

  derived
}

# 3.3 TRUE MICE-PMM multiple imputation.
#     IMPORTANT:
#     - ONLY the 18 BASIC/source variables are supplied to this function.
#     - The six derived predictors are absent from mice() and cannot be imputed.
#     - Outcome PDstage, patient ID, and stage source are never used for imputation.
#     - ALL m completed datasets are returned; none are discarded.
mice_impute_predictors <- function(
    predictor_df,
    ignore_vec = NULL,
    seed = SEED,
    m = MICE_M,
    maxit = MICE_MAXIT,
    method_name = MICE_METHOD,
    print_flag = MICE_PRINT_FLAG,
    eps = MICE_EPS
) {
  dat <- as.data.frame(predictor_df)

  if (m < 1 || m != as.integer(m)) {
    stop("m must be a positive integer.")
  }

  # All 18 BASIC/source variables are numeric in this analysis, including binary 0/1 variables.
  for (nm in names(dat)) {
    dat[[nm]] <- suppressWarnings(as.numeric(dat[[nm]]))
  }

  if (is.null(ignore_vec)) {
    ignore_vec <- rep(FALSE, nrow(dat))
  }

  if (length(ignore_vec) != nrow(dat)) {
    stop("ignore_vec length does not match number of rows.")
  }

  # If there are no missing values, still return m identical completed datasets.
  # This keeps downstream multiple-imputation logic structurally consistent.
  if (!anyNA(dat)) {
    completed_list <- lapply(
      seq_len(m),
      function(j) as_tibble(dat)
    )
    names(completed_list) <- paste0("Imp", seq_len(m))

    return(list(
      completed_list = completed_list,
      mids = NULL,
      method = setNames(rep("", ncol(dat)), names(dat)),
      predictorMatrix = NULL,
      loggedEvents = NULL,
      m = m
    ))
  }

  method_vec <- mice::make.method(dat)
  method_vec[] <- ""

  has_missing <- vapply(dat, anyNA, logical(1))
  method_vec[has_missing] <- method_name

  pred_mat <- mice::make.predictorMatrix(dat)
  diag(pred_mat) <- 0

  # No outcome is present in dat, so outcome leakage is impossible here.
  set.seed(seed)
  imp <- mice::mice(
    dat,
    method = method_vec,
    predictorMatrix = pred_mat,
    m = m,
    maxit = maxit,
    ignore = ignore_vec,
    seed = seed,
    printFlag = print_flag,
    eps = eps
  )

  # TRUE multiple imputation: extract every completed dataset, not only action = 1.
  completed_list <- lapply(
    seq_len(m),
    function(j) {
      out <- mice::complete(imp, action = j) |>
        as_tibble()

      if (anyNA(out)) {
        stop(sprintf("MICE completed dataset %d still contains missing values.", j))
      }
      out
    }
  )
  names(completed_list) <- paste0("Imp", seq_len(m))

  list(
    completed_list = completed_list,
    mids = imp,
    method = method_vec,
    predictorMatrix = pred_mat,
    loggedEvents = imp$loggedEvents,
    m = m
  )
}


# 3.4 Build a CV object with fold-wise TRUE multiple imputation.
#
#     For each original CV fold:
#       analysis rows    -> ignore = FALSE -> estimate MICE models
#       assessment rows  -> ignore = TRUE  -> imputed but do not estimate models
#
#     Each fold yields MICE_M completed datasets. Therefore a 5-fold CV with
#     MICE_M = 5 produces 25 modeling resamples:
#       Fold01_Imp01 ... Fold01_Imp05
#       ...
#       Fold05_Imp01 ... Fold05_Imp05
#
#     Bayesian tuning evaluates all fold-imputation resamples. After the best
#     hyperparameters are selected, each patient's MICE_M OOF probabilities are
#     averaged to obtain one pooled OOF probability per base learner.
build_foldwise_mice_rset <- function(
    raw_model_df,
    raw_imputation_df,
    predictor_names,
    imputation_names,
    v = CV_FOLDS,
    m = MICE_M,
    seed = SEED
) {
  if (nrow(raw_model_df) != nrow(raw_imputation_df)) {
    stop("raw_model_df and raw_imputation_df must have identical row counts.")
  }

  source_for_split <- raw_model_df |>
    mutate(.row_id = seq_len(n()))

  set.seed(seed)
  base_folds <- vfold_cv(source_for_split, v = v, strata = PDstage)

  custom_splits <- list()
  custom_ids <- character(0)
  imputation_logs <- list()
  imputation_map <- list()
  mice_call_logs <- list()

  split_counter <- 0L

  for (i in seq_len(nrow(base_folds))) {
    cat(sprintf(
      "MICE preprocessing for Fold %d/%d: generating %d imputations ...\n",
      i, nrow(base_folds), m
    ))

    sp <- base_folds$splits[[i]]
    analysis_idx <- sort(rsample::analysis(sp)$.row_id)
    assessment_idx <- sort(rsample::assessment(sp)$.row_id)

    ignore_vec <- rep(TRUE, nrow(raw_model_df))
    ignore_vec[analysis_idx] <- FALSE

    # One MICE call creates m completed BASIC-variable datasets/chains for this fold.
    # None of AG_ratio/eGFR/PAR/NPR/INR/TyG is present in this mice() call.
    imp_i <- mice_impute_predictors(
      predictor_df = raw_imputation_df |> select(all_of(imputation_names)),
      ignore_vec = ignore_vec,
      seed = seed + i,
      m = m,
      eps = MICE_EPS
    )

    # Save one MICE diagnostic record per outer fold.
    mice_call_logs[[i]] <- list(
      Fold = i,
      Analysis_N = length(analysis_idx),
      Assessment_N = length(assessment_idx),
      MICE_method = imp_i$method,
      MICE_predictorMatrix = imp_i$predictorMatrix,
      MICE_eps = MICE_EPS,
      MICE_loggedEvents = imp_i$loggedEvents
    )

    for (j in seq_len(m)) {
      completed_basic <- imp_i$completed_list[[j]]

      # IMPORTANT: derive all six non-imputed predictors only AFTER MICE.
      # Observed values of AG_ratio/eGFR/PAR/NPR/INR/TyG in the source file
      # are intentionally ignored; the model uses deterministic recalculation
      # from the completed BASIC variables in every imputation.
      completed_predictors <- derive_model_predictors(
        completed_basic,
        strict = TRUE
      ) |>
        select(all_of(predictor_names))

      fold_data <- bind_cols(
        raw_model_df |> select(PDstage),
        completed_predictors
      )

      if (anyNA(fold_data)) {
        stop(sprintf(
          "Missing values remain in fold %d, imputation %d.",
          i, j
        ))
      }

      split_counter <- split_counter + 1L
      split_id <- sprintf("Fold%02d_Imp%02d", i, j)

      custom_splits[[split_counter]] <- rsample::make_splits(
        x = list(analysis = analysis_idx, assessment = assessment_idx),
        data = fold_data
      )
      custom_ids[split_counter] <- split_id

      imputation_map[[split_counter]] <- tibble(
        id = split_id,
        Fold = i,
        Imputation = j,
        Analysis_N = length(analysis_idx),
        Assessment_N = length(assessment_idx)
      )

      imputation_logs[[split_counter]] <- list(
        id = split_id,
        fold = i,
        imputation = j,
        analysis_n = length(analysis_idx),
        assessment_n = length(assessment_idx),
        method = imp_i$method,
        loggedEvents = imp_i$loggedEvents,
        derived_predictors = derived_vars
      )
    }
  }

  custom_rset <- rsample::manual_rset(
    splits = custom_splits,
    ids = custom_ids
  )

  list(
    rset = custom_rset,
    original_folds = base_folds,
    imputation_logs = imputation_logs,
    imputation_map = bind_rows(imputation_map),
    mice_call_logs = mice_call_logs
  )
}


# 3.5 Pool MICE-specific OOF probabilities to one probability per patient.
#     For machine-learning models, Rubin's coefficient pooling is generally not
#     available. We therefore fit/predict separately in every completed dataset
#     and integrate imputation uncertainty by averaging predicted probabilities.
pool_mi_oof_predictions <- function(
    pred_tbl,
    prob_col = ".pred_Stage1",
    pooled_name,
    expected_m = MICE_M
) {
  if (!(prob_col %in% names(pred_tbl))) {
    stop(paste0("Probability column not found: ", prob_col))
  }

  out <- pred_tbl |>
    group_by(.row, PDstage) |>
    summarise(
      MI_N = n(),
      Pooled_Probability = mean(.data[[prob_col]], na.rm = TRUE),
      MI_SD = ifelse(n() > 1, sd(.data[[prob_col]], na.rm = TRUE), 0),
      .groups = "drop"
    ) |>
    arrange(.row)

  if (any(out$MI_N != expected_m)) {
    bad <- out |> filter(MI_N != expected_m)
    stop(
      paste0(
        "OOF MI pooling count is incorrect. Expected ", expected_m,
        " predictions per patient; found mismatches for ",
        nrow(bad), " rows."
      )
    )
  }

  names(out)[names(out) == "Pooled_Probability"] <- pooled_name
  names(out)[names(out) == "MI_SD"] <- paste0(pooled_name, "_MI_SD")
  names(out)[names(out) == "MI_N"] <- paste0(pooled_name, "_MI_N")

  out
}


# 3.6 Metrics for model-building OOF probabilities.
#     These are development-stage diagnostics, NOT external validation results.
calculate_metrics <- function(truth, prob, threshold) {
  truth_chr <- as.character(truth)
  truth_num <- ifelse(truth_chr == "Stage1", 1, 0)

  pred_chr <- ifelse(prob >= threshold, "Stage1", "Stage0")

  TP <- sum(pred_chr == "Stage1" & truth_chr == "Stage1")
  TN <- sum(pred_chr == "Stage0" & truth_chr == "Stage0")
  FP <- sum(pred_chr == "Stage1" & truth_chr == "Stage0")
  FN <- sum(pred_chr == "Stage0" & truth_chr == "Stage1")

  sens <- TP / (TP + FN)
  spec <- TN / (TN + FP)
  acc <- (TP + TN) / (TP + TN + FP + FN)
  ppv <- TP / (TP + FP)
  npv <- TN / (TN + FN)
  f1 <- 2 * ppv * sens / (ppv + sens)
  gmean <- sqrt(sens * spec)

  roc_obj <- pROC::roc(
    response = factor(truth_chr, levels = c("Stage0", "Stage1")),
    predictor = prob,
    levels = c("Stage0", "Stage1"),
    direction = "<",
    quiet = TRUE
  )

  auc_value <- as.numeric(pROC::auc(roc_obj))
  brier <- mean((prob - truth_num)^2)

  # 10-bin ECE
  bins <- cut(
    prob,
    breaks = seq(0, 1, length.out = 11),
    include.lowest = TRUE,
    right = TRUE
  )

  ece_df <- tibble(
    prob = prob,
    truth = truth_num,
    bin = bins
  ) |>
    group_by(bin) |>
    summarise(
      n = n(),
      mean_prob = mean(prob),
      mean_obs = mean(truth),
      .groups = "drop"
    )

  ece <- sum(
    (ece_df$n / length(prob)) * abs(ece_df$mean_prob - ece_df$mean_obs)
  )

  tibble(
    Metric = c(
      "AUC", "Sensitivity", "Specificity", "Accuracy",
      "F1", "NPV", "PPV", "G_mean", "Brier", "ECE"
    ),
    Value = c(
      auc_value, sens, spec, acc,
      f1, npv, ppv, gmean, brier, ece
    )
  )
}

# 3.7 Convert best-parameter tibble into a long table for Excel.
best_params_to_long <- function(best_tbl, model_name) {
  x <- best_tbl
  if (".config" %in% names(x)) {
    x <- x |> select(-.config)
  }

  tibble(
    Model = model_name,
    Parameter = names(x),
    Value = vapply(x, function(z) as.character(z[[1]]), character(1))
  )
}

# ------------------------------------------------------------------------------
# 4. Read raw development data
# ------------------------------------------------------------------------------
cat("\n==================== 1. READ RAW DATA ====================\n")

raw_data <- readxl::read_excel(
  DATA_PATH,
  na = c("", "NA", "N/A", "na", "NaN", "NULL")
)

required_cols <- unique(c(
  outcome_var,
  imputation_vars
))

missing_cols <- setdiff(required_cols, names(raw_data))

if (length(missing_cols) > 0) {
  stop(
    paste0(
      "The following required BASIC/source columns are absent from the Excel file: ",
      paste(missing_cols, collapse = ", ")
    )
  )
}

# Force the 18 BASIC/source variables to numeric.
raw_data <- raw_data |>
  mutate(
    across(
      all_of(imputation_vars),
      ~ suppressWarnings(as.numeric(.x))
    )
  )

# Check binary coding before imputation/derivation.
for (nm in binary_vars) {
  vals <- sort(unique(raw_data[[nm]][!is.na(raw_data[[nm]])]))
  if (!all(vals %in% c(0, 1))) {
    stop(paste0(nm, " must be coded as 0/1."))
  }
}

# IMPORTANT: confirm Sex coding used by the eGFR equation.
cat(
  "eGFR Sex coding: female =", SEX_FEMALE_CODE,
  "| male =", SEX_MALE_CODE,
  "| race coefficient =", EGFR_RACE_COEFFICIENT, "\n"
)

# Raw MICE input: ONLY the 18 BASIC/source variables.
raw_imputation_df <- raw_data |>
  select(all_of(imputation_vars))

# Build the raw final-predictor view ONLY for auditing / recipe specification.
# Missing BASIC values naturally propagate to their derived predictors here.
# No derived value from the source file is used.
raw_derived_predictors <- derive_model_predictors(
  raw_imputation_df,
  strict = FALSE
)

model_raw <- bind_cols(
  tibble(PDstage = to_stage_factor(raw_data[[outcome_var]])),
  raw_derived_predictors
)

if (anyNA(model_raw$PDstage)) {
  stop("Outcome PDstage contains missing values.")
}

cat("Rows in development cohort:", nrow(raw_data), "\n")
cat(
  "MICE input variables (BASIC only):",
  paste(imputation_vars, collapse = ", "), "\n"
)
cat(
  "Derived after MICE (never imputed):",
  paste(derived_vars, collapse = ", "), "\n"
)

class_table <- as.data.frame(table(model_raw$PDstage))
names(class_table) <- c("Class", "N")

missing_before <- tibble(
  Variable = predictor_vars,
  Missing_N = vapply(
    model_raw |> select(all_of(predictor_vars)),
    function(x) sum(is.na(x)),
    integer(1)
  )
) |>
  mutate(Missing_Rate = Missing_N / nrow(model_raw))

mice_input_missing_before <- tibble(
  Variable = imputation_vars,
  Missing_N = vapply(
    raw_imputation_df,
    function(x) sum(is.na(x)),
    integer(1)
  )
) |>
  mutate(Missing_Rate = Missing_N / nrow(raw_imputation_df))

print(class_table)
print(missing_before |> filter(Missing_N > 0))

# ------------------------------------------------------------------------------
# 5. Build fold-wise TRUE-MI resamples
# ------------------------------------------------------------------------------
cat("\n==================== 2. FOLD-WISE TRUE-MI CV ====================\n")

foldwise <- build_foldwise_mice_rset(
  raw_model_df = model_raw,
  raw_imputation_df = raw_imputation_df,
  predictor_names = predictor_vars,
  imputation_names = imputation_vars,
  v = CV_FOLDS,
  m = MICE_M,
  seed = SEED
)

cv_folds <- foldwise$rset

cat(
  "Original CV folds:", CV_FOLDS,
  "| MICE imputations per fold:", MICE_M,
  "| Total tuning resamples:", nrow(cv_folds), "\n"
)

# ------------------------------------------------------------------------------
# 6. Common recipe: scaling + SMOTE + Tomek
# ------------------------------------------------------------------------------
# MICE has already generated multiple completed datasets inside each original CV fold.
# Scaling and class-imbalance correction remain inside the recipe and are
# therefore estimated/applied separately during resampling.
common_recipe <- recipe(PDstage ~ ., data = model_raw) |>
  step_normalize(!!!rlang::syms(continuous_vars)) |>
  step_smote(PDstage, over_ratio = 1, neighbors = 5, skip = TRUE, seed = SEED) |>
  step_tomek(PDstage, skip = TRUE, seed = SEED) |>
  # The original analysis treated Sex/Smoke as numeric during SMOTE and then
  # returned any synthetic fractional values to 0/1.
  step_mutate(
    Sex = round(Sex),
    Smoke = round(Smoke)
  )

# ------------------------------------------------------------------------------
# 7. Parallel backend (future; compatible with tune >= 2.1.0)
# ------------------------------------------------------------------------------
physical_cores <- parallel::detectCores(logical = FALSE)
if (is.na(physical_cores) || physical_cores < 1) physical_cores <- 1L

if (is.null(PARALLEL_WORKERS)) {
  n_workers <- max(1L, as.integer(physical_cores) - 1L)
} else {
  n_workers <- as.integer(PARALLEL_WORKERS)
  if (!is.finite(n_workers) || n_workers < 1L) {
    stop("PARALLEL_WORKERS must be NULL or a positive integer.")
  }
  n_workers <- min(n_workers, max(1L, as.integer(physical_cores)))
}

future::plan(
  future::multisession,
  workers = n_workers
)

cat(
  "Parallel framework: future::multisession",
  "| physical cores:", physical_cores,
  "| workers:", n_workers,
  "| tune parallel_over:", TUNE_PARALLEL_OVER,
  "\n"
)

modeling_error <- NULL

tryCatch({

  # ============================================================================
  # 8. SVM RBF tuning
  # ============================================================================
  cat("\n==================== 3. TUNE SVM ====================\n")

  svm_spec <- svm_rbf(
    cost = tune(),
    rbf_sigma = tune()
  ) |>
    set_engine("kernlab") |>
    set_mode("classification")

  svm_wf <- workflow() |>
    add_recipe(common_recipe) |>
    add_model(svm_spec)

  # Keep the dials defaults used by the original SVM script:
  # cost:      log2 scale, default range [-10, 5]
  # rbf_sigma: log10 scale, default range [-10, 0]
  svm_param_set <- extract_parameter_set_dials(svm_spec) |>
    update(
      # Avoid numerically extreme pairs that can trigger kernlab's
      # internal sigmoid probability-calibration line-search failure.
      # The previously stable optimum remains comfortably inside this range.
      cost = cost(range = c(-1, 7)),             # 0.25 to 128
      rbf_sigma = rbf_sigma(range = c(-4.7, -2.7))  # 1e-5 to 1e-2
    )
  
  set.seed(SEED)
  svm_tune <- tune_bayes(
    svm_wf,
    resamples = cv_folds,
    param_info = svm_param_set,
    initial = SVM_BAYES_INITIAL,
    iter = SVM_BAYES_ITER,
    metrics = metric_set(roc_auc),
    control = control_bayes(
      save_pred = TRUE,
      verbose = TRUE,
      no_improve = 25,
      uncertain = 8,
      seed = SEED,
      event_level = "first",
      allow_par = TRUE,
      parallel_over = TUNE_PARALLEL_OVER,
      pkgs = c("kernlab", "recipes", "themis")
    )
  )

  print_tune_notes_if_any(svm_tune, "SVM")

  svm_best <- select_by_pct_loss(
    svm_tune,
    metric = "roc_auc",
    limit = 0.1,
    cost,
    rbf_sigma
  )
  
  svm_best_config <- show_best(
    svm_tune,
    metric = "roc_auc",
    n = 1
  )$.config[[1]]

  cat("\nBest SVM parameters:\n")
  print(svm_best)

  svm_final_wf <- finalize_workflow(svm_wf, svm_best)

  # Each patient has MICE_M OOF predictions, one from each imputed
  # version of the same held-out fold. Pool them by mean probability.
  svm_oof_raw <- collect_predictions(svm_tune) |>
    filter(.config == svm_best_config) |>
    select(.row, PDstage, id, .pred_Stage1) |>
    arrange(.row, id)

  svm_oof <- pool_mi_oof_predictions(
    pred_tbl = svm_oof_raw,
    prob_col = ".pred_Stage1",
    pooled_name = "SVM",
    expected_m = MICE_M
  )

  # ============================================================================
  # 9. XGBoost tuning
  # ============================================================================
  cat("\n==================== 4. TUNE XGBOOST ====================\n")

  xgb_spec <- boost_tree(
    trees = tune(),
    tree_depth = tune(),
    learn_rate = tune(),
    min_n = tune(),
    loss_reduction = tune(),
    sample_size = tune(),
    mtry = tune()
  ) |>
    # Parallelization is handled outside xgboost to avoid nested oversubscription.
    set_engine(
      "xgboost",
      nthread = 1,
      verbosity = 0,
      counts = FALSE
    ) |>
    set_mode("classification")

  xgb_wf <- workflow() |>
    add_recipe(common_recipe) |>
    add_model(xgb_spec)

  # Preserve the search ranges used in the uploaded XGBoost script.
  xgb_param_set <- extract_parameter_set_dials(xgb_spec) |>
    update(
      trees = trees(range = c(200L, 1500L)),
      tree_depth = tree_depth(range = c(2L, 6L)),
      learn_rate = learn_rate(range = c(-3, -1)),
      loss_reduction = loss_reduction(range = c(-4, 0.7)),
      min_n = min_n(range = c(1L, 50L)),
      sample_size = sample_prop(range = c(0.4, 0.9)),
      mtry = mtry_prop(range = c(0.4, 1.0))
    )

  set.seed(SEED)
  xgb_tune <- tune_bayes(
    xgb_wf,
    resamples = cv_folds,
    param_info = xgb_param_set,
    initial = XGB_BAYES_INITIAL,
    iter = XGB_BAYES_ITER,
    metrics = metric_set(roc_auc),
    control = control_bayes(
      save_pred = TRUE,
      verbose = TRUE,
      no_improve = 45,
      uncertain = 10,
      seed = SEED,
      event_level = "first",
      allow_par = TRUE,
      parallel_over = TUNE_PARALLEL_OVER,
      pkgs = c("xgboost", "recipes", "themis")
    )
  )

  print_tune_notes_if_any(xgb_tune, "XGBoost")

  xgb_best <- select_by_pct_loss(
    xgb_tune,
    metric = "roc_auc",
    limit = 0.1,
    trees,
    tree_depth,
    desc(min_n),
    desc(loss_reduction)
  )
  
  xgb_best_config <- show_best(
    xgb_tune,
    metric = "roc_auc",
    n = 1
  )$.config[[1]]

  cat("\nBest XGBoost parameters:\n")
  print(xgb_best)

  xgb_final_wf <- finalize_workflow(xgb_wf, xgb_best)

  # Pool the MICE_M OOF predictions per patient.
  xgb_oof_raw <- collect_predictions(xgb_tune) |>
    filter(.config == xgb_best_config) |>
    select(.row, PDstage, id, .pred_Stage1) |>
    arrange(.row, id)

  xgb_oof <- pool_mi_oof_predictions(
    pred_tbl = xgb_oof_raw,
    prob_col = ".pred_Stage1",
    pooled_name = "XGB",
    expected_m = MICE_M
  )

  # ============================================================================
  # 10. Align OOF base predictions
  # ============================================================================
  cat("\n==================== 5. BUILD STACKING DATA ====================\n")

  base_oof <- inner_join(
    svm_oof,
    xgb_oof,
    by = c(".row", "PDstage")
  ) |>
    arrange(.row)

  if (nrow(base_oof) != nrow(model_raw)) {
    stop(
      paste0(
        "OOF merge failed: expected ", nrow(model_raw),
        " rows but obtained ", nrow(base_oof), "."
      )
    )
  }

  if (any(base_oof$SVM_MI_N != MICE_M) || any(base_oof$XGB_MI_N != MICE_M)) {
    stop("At least one patient does not have the expected number of MI OOF predictions.")
  }

  cat(
    "OOF pooling completed:",
    nrow(base_oof), "patients x", MICE_M, "imputations per base learner.\n"
  )

  # Preserve the original stacking strategy:
  # Z-standardize base-learner OOF probabilities before the Elastic Net layer.
  meta_scaler <- list(
    SVM_mean = mean(base_oof$SVM),
    SVM_sd = sd(base_oof$SVM),
    XGB_mean = mean(base_oof$XGB),
    XGB_sd = sd(base_oof$XGB)
  )

  if (meta_scaler$SVM_sd <= 0 || meta_scaler$XGB_sd <= 0) {
    stop("A base-model OOF probability has zero variance.")
  }

  meta_df <- base_oof |>
    mutate(
      SVM_z = (SVM - meta_scaler$SVM_mean) / meta_scaler$SVM_sd,
      XGB_z = (XGB - meta_scaler$XGB_mean) / meta_scaler$XGB_sd
    ) |>
    select(.row, PDstage, SVM, XGB, SVM_z, XGB_z)

  # ============================================================================
  # 11. Elastic Net meta-learner
  # ============================================================================
  cat("\n==================== 6. TUNE ELASTIC NET META-LEARNER ====================\n")

  meta_spec <- logistic_reg(
    penalty = tune(),
    mixture = tune()
  ) |>
    set_engine("glmnet") |>
    set_mode("classification")

  meta_recipe <- recipe(PDstage ~ SVM_z + XGB_z, data = meta_df)

  meta_wf <- workflow() |>
    add_recipe(meta_recipe) |>
    add_model(meta_spec)

  set.seed(SEED)
  meta_folds <- vfold_cv(
    meta_df,
    v = 5,
    repeats = 3,
    strata = PDstage
  )

  meta_grid <- grid_regular(
    penalty(range = c(-4, 1)),
    mixture(range = c(0, 0.6)),
    levels = c(penalty = 30, mixture = 15)
  )

  set.seed(SEED)
  meta_tune <- tune_grid(
    meta_wf,
    resamples = meta_folds,
    grid = meta_grid,
    metrics = metric_set(
      roc_auc,
      mn_log_loss,
      brier_class
    ),
    control = control_grid(
      save_pred = TRUE,
      verbose = TRUE,
      event_level = "first",
      allow_par = TRUE,
      parallel_over = TUNE_PARALLEL_OVER,
      pkgs = c("glmnet", "recipes")
    )
  )

  print_tune_notes_if_any(meta_tune, "Elastic Net meta")

  meta_best <- select_best(
    meta_tune,
    metric = "mn_log_loss"
  )
  
  meta_best_config <- show_best(
    meta_tune,
    metric = "mn_log_loss",
    n = 1
  )$.config[[1]]

  cat("\nBest Elastic Net parameters:\n")
  print(meta_best)

  meta_final_wf <- finalize_workflow(meta_wf, meta_best)

  # Repeated 5-fold CV gives each patient multiple OOF predictions.
  # Average the repeated OOF estimates for calibration and threshold selection.
  meta_oof <- collect_predictions(meta_tune) |>
    filter(.config == meta_best_config) |>
    group_by(.row) |>
    summarise(
      PDstage = first(PDstage),
      Stack_raw = mean(.pred_Stage1),
      .groups = "drop"
    ) |>
    arrange(.row)

  if (nrow(meta_oof) != nrow(model_raw)) {
    stop("Meta-learner OOF prediction row count is incorrect.")
  }

  # Fit final meta-learner to all aligned base OOF predictions.
  meta_fit <- fit(
    meta_final_wf,
    data = meta_df
  )

  # ============================================================================
  # 12. Platt scaling + frozen threshold
  # ============================================================================
  cat("\n==================== 7. PLATT CALIBRATION ====================\n")

  platt_df <- meta_oof |>
    mutate(
      labels = ifelse(PDstage == "Stage1", 1, 0),
      probs = Stack_raw
    )

  # This preserves the implementation used in the uploaded calibration script:
  # logistic regression of observed outcome on the raw stacking probability.
  platt_calibrator <- glm(
    labels ~ probs,
    data = platt_df,
    family = binomial(link = "logit")
  )

  meta_oof$Stack_calibrated <- predict(
    platt_calibrator,
    newdata = data.frame(probs = meta_oof$Stack_raw),
    type = "response"
  )

  roc_for_threshold <- pROC::roc(
    response = factor(
      as.character(meta_oof$PDstage),
      levels = c("Stage0", "Stage1")
    ),
    predictor = meta_oof$Stack_calibrated,
    levels = c("Stage0", "Stage1"),
    direction = "<",
    quiet = TRUE
  )

  threshold_info <- pROC::coords(
    roc_for_threshold,
    x = "best",
    best.method = "youden",
    ret = c("threshold", "sensitivity", "specificity"),
    transpose = FALSE
  )

  final_threshold <- as.numeric(threshold_info$threshold[1])

  cat("Frozen Youden threshold:", final_threshold, "\n")

  development_oof_metrics <- calculate_metrics(
    truth = meta_oof$PDstage,
    prob = meta_oof$Stack_calibrated,
    threshold = final_threshold
  )

  # ============================================================================
  # 13. Final TRUE multiple imputation on the ENTIRE development cohort
  # ============================================================================
  cat("\n==================== 8. FINAL FULL-COHORT MULTIPLE IMPUTATION ====================\n")

  # One MICE object generates MICE_M completed full-cohort BASIC-variable datasets.
  # None of the six derived predictors is supplied to mice().
  final_imp <- mice_impute_predictors(
    predictor_df = raw_imputation_df |> select(all_of(imputation_vars)),
    ignore_vec = rep(FALSE, nrow(model_raw)),
    seed = SEED + 100,
    m = MICE_M,
    eps = MICE_EPS
  )

  dev_complete_list <- vector("list", MICE_M)
  dev_basic_complete_list <- vector("list", MICE_M)

  for (j in seq_len(MICE_M)) {
    final_basic_complete_j <- final_imp$completed_list[[j]]

    # Derive AG_ratio/eGFR/PAR/NPR/INR/TyG AFTER MICE from completed BASIC data.
    final_predictors_complete_j <- derive_model_predictors(
      final_basic_complete_j,
      strict = TRUE
    )

    dev_complete_j <- bind_cols(
      model_raw |> select(PDstage),
      final_predictors_complete_j
    )

    if (anyNA(dev_complete_j)) {
      stop(sprintf(
        "Missing values remain after final MICE + deterministic derivation in imputation %d.",
        j
      ))
    }

    dev_basic_complete_list[[j]] <- as_tibble(final_basic_complete_j)
    dev_complete_list[[j]] <- dev_complete_j
  }

  names(dev_basic_complete_list) <- paste0("Imp", seq_len(MICE_M))
  names(dev_complete_list) <- paste0("Imp", seq_len(MICE_M))

  # ============================================================================
  # 14. Refit one SVM and one XGBoost model in EACH completed dataset
  # ============================================================================
  cat("\n==================== 9. REFIT FINAL BASE MODELS ACROSS IMPUTATIONS ====================\n")

  final_svm_fits <- vector("list", MICE_M)
  final_xgb_fits <- vector("list", MICE_M)

  for (j in seq_len(MICE_M)) {
    cat(sprintf("Final refit: imputation %d/%d ...\n", j, MICE_M))

    set.seed(SEED + 1000 + j)
    final_svm_fits[[j]] <- fit(
      svm_final_wf,
      data = dev_complete_list[[j]]
    )

    set.seed(SEED + 2000 + j)
    final_xgb_fits[[j]] <- fit(
      xgb_final_wf,
      data = dev_complete_list[[j]]
    )
  }

  names(final_svm_fits) <- paste0("Imp", seq_len(MICE_M))
  names(final_xgb_fits) <- paste0("Imp", seq_len(MICE_M))

  # ============================================================================
  # 15. Prepare audit table
  # ============================================================================
  best_params_table <- bind_rows(
    best_params_to_long(svm_best, "SVM"),
    best_params_to_long(xgb_best, "XGBoost"),
    best_params_to_long(meta_best, "ElasticNet_Meta")
  )

  # ============================================================================
  # 16. Save the frozen model bundle
  # ============================================================================
  # IMPORTANT: the serialized model bundle contains patient-level information
  # (including imputed datasets and fitted SVM support-vector information).
  # Keep this file under private/ and do not commit it to the public repository.
  cat("\n==================== 10. FREEZE MODEL ====================\n")

  meta_engine <- extract_fit_engine(meta_fit)
  
  coef_mat <- as.matrix(
    coef(
      meta_engine,
      s = meta_best$penalty
    )
  )
  
  meta_coef <- tibble(
    term = rownames(coef_mat),
    estimate = as.numeric(coef_mat[, 1]),
    penalty = meta_best$penalty,
    mixture = meta_best$mixture
  )

  model_bundle <- list(
    model_name = paste0("SVM + XGBoost stacking model; multiple imputation m=", MICE_M),
    created_at = Sys.time(),
    seed = SEED,

    # Fixed predictor/model specification
    outcome = outcome_var,
    predictors = predictor_vars,
    binary_predictors = binary_vars,
    continuous_predictors = continuous_vars,
    architecture = list(
      base_learners = c("SVM_RBF", "XGBoost"),
      meta_learner = "Elastic Net logistic regression",
      calibration = "Platt scaling",
      class_imbalance = "SMOTE + Tomek"
    ),

    # Deterministic derivation rules
    derived_predictors = derived_vars,
    imputation_variables = imputation_vars,
    derivation_rules = list(
      AG_ratio = "ALB/(TP-ALB)",
      INR = "(PT/13.1)^1.31",
      NPR = "NE_C/PLT",
      PAR = "PLT/ALB",
      TyG = "log(1594.26*TG*GLU/2)",
      eGFR = paste0(
        "141*min((CR/88.4)/kappa,1)^alpha*max((CR/88.4)/kappa,1)^(-1.209)",
        "*0.993^Age*sex_coefficient*race_coefficient"
      )
    ),
    egfr_settings = list(
      female_code = SEX_FEMALE_CODE,
      male_code = SEX_MALE_CODE,
      female_kappa = 0.7,
      male_kappa = 0.9,
      female_alpha = -0.329,
      male_alpha = -0.411,
      female_coefficient = 1.018,
      male_coefficient = 1.0,
      race_coefficient = EGFR_RACE_COEFFICIENT,
      creatinine_conversion = "CR_umol_L / 88.4 = Scr_mg_dL"
    ),

    # TRUE multiple-imputation deployment information
    mice_settings = list(
      m = MICE_M,
      maxit = MICE_MAXIT,
      eps = MICE_EPS,
      method = MICE_METHOD,
      printFlag = MICE_PRINT_FLAG,
      pooling_rule = MI_POOLING_RULE,
      cv_folds = CV_FOLDS,
      outcome_used_for_imputation = FALSE,
      derived_predictors_imputed = FALSE
    ),
    raw_development_predictors = model_raw |> select(all_of(predictor_vars)),
    raw_development_imputation_data = raw_imputation_df,
    final_mice_object = final_imp$mids,
    final_completed_basic_datasets = dev_basic_complete_list,

    # Base models: one fitted SVM and XGBoost per completed dataset.
    svm_best_params = svm_best,
    xgb_best_params = xgb_best,
    final_svm_fits = final_svm_fits,
    final_xgb_fits = final_xgb_fits,

    # Stacking
    meta_scaler = meta_scaler,
    meta_best_params = meta_best,
    meta_fit = meta_fit,

    # Calibration / classification
    platt_calibrator = platt_calibrator,
    final_threshold = final_threshold,

    # Audit data
    base_oof_predictions = base_oof,
    svm_oof_predictions_by_imputation = svm_oof_raw,
    xgb_oof_predictions_by_imputation = xgb_oof_raw,
    fold_imputation_map = foldwise$imputation_map,
    fold_mice_call_logs = foldwise$mice_call_logs,
    final_mice_loggedEvents = final_imp$loggedEvents,
    meta_oof_predictions = meta_oof,
    development_oof_metrics = development_oof_metrics,
    missing_before_imputation = missing_before,
    basic_missing_before_imputation = mice_input_missing_before
  )

  saveRDS(
    model_bundle,
    file = file.path(MODEL_DIR, "final_stacking_model_bundle.rds")
  )

  # Save tuning objects separately; they are useful for audit/reproducibility but
  # are not needed to deploy the frozen model.
  saveRDS(
    svm_tune,
    file = file.path(MODEL_DIR, "svm_bayesian_tuning.rds")
  )

  saveRDS(
    xgb_tune,
    file = file.path(MODEL_DIR, "xgboost_bayesian_tuning.rds")
  )

  saveRDS(
    meta_tune,
    file = file.path(MODEL_DIR, "meta_learner_tuning.rds")
  )

  # ============================================================================
  # 17. Export audit tables
  # ============================================================================
  threshold_table <- tibble(
    Item = c(
      "Youden_threshold",
      "OOF_sensitivity_at_threshold",
      "OOF_specificity_at_threshold"
    ),
    Value = c(
      final_threshold,
      as.numeric(threshold_info$sensitivity[1]),
      as.numeric(threshold_info$specificity[1])
    )
  )

  mi_settings_table <- tibble(
    Parameter = c(
      "MICE_M",
      "MICE_MAXIT",
      "MICE_EPS",
      "MICE_METHOD",
      "MICE_PRINT_FLAG",
      "CV_FOLDS",
      "Total_fold_imputation_resamples",
      "MI_POOLING_RULE",
      "Outcome_used_for_imputation",
      "Derived_predictors_imputed",
      "MICE_input_variable_count",
      "Derived_variable_count"
    ),
    Value = as.character(c(
      MICE_M,
      MICE_MAXIT,
      MICE_EPS,
      MICE_METHOD,
      MICE_PRINT_FLAG,
      CV_FOLDS,
      nrow(cv_folds),
      MI_POOLING_RULE,
      FALSE,
      FALSE,
      length(imputation_vars),
      length(derived_vars)
    ))
  )

  derivation_rules_table <- tibble(
    Derived_predictor = c("AG_ratio", "eGFR", "PAR", "NPR", "INR", "TyG"),
    Imputed_by_MICE = FALSE,
    Source_variables = c(
      "ALB, TP",
      "CR, Age, Sex",
      "PLT, ALB",
      "NE_C, PLT",
      "PT",
      "TG, GLU"
    ),
    Rule = c(
      "ALB/(TP-ALB)",
      paste0(
        "141*min((CR/88.4)/kappa,1)^alpha*max((CR/88.4)/kappa,1)^(-1.209)",
        "*0.993^Age*sex_coefficient*race_coefficient"
      ),
      "PLT/ALB",
      "NE_C/PLT",
      "(PT/13.1)^1.31",
      "log(1594.26*TG*GLU/2)"
    )
  )

  mice_input_variables_table <- tibble(
    MICE_input_variable = imputation_vars,
    Eligible_for_MICE_if_missing = TRUE
  )

  # MICE diagnostic audit: one record per outer-fold mice() call.
  mice_log_summary <- purrr::map_dfr(
    seq_along(foldwise$mice_call_logs),
    function(i) {
      x <- foldwise$mice_call_logs[[i]]$MICE_loggedEvents
      tibble(
        Fold = i,
        Analysis_N = foldwise$mice_call_logs[[i]]$Analysis_N,
        Assessment_N = foldwise$mice_call_logs[[i]]$Assessment_N,
        MICE_eps = MICE_EPS,
        Logged_events = if (is.null(x)) 0L else nrow(x)
      )
    }
  )

  mice_logged_events_all <- purrr::map_dfr(
    seq_along(foldwise$mice_call_logs),
    function(i) {
      x <- foldwise$mice_call_logs[[i]]$MICE_loggedEvents
      if (is.null(x) || nrow(x) == 0) return(tibble())
      as_tibble(x) |> mutate(Fold = i, .before = 1)
    }
  )

  final_mice_logged_events <- if (
    is.null(final_imp$loggedEvents) || nrow(final_imp$loggedEvents) == 0
  ) {
    tibble()
  } else {
    as_tibble(final_imp$loggedEvents)
  }

  if (nrow(mice_logged_events_all) > 0 || nrow(final_mice_logged_events) > 0) {
    warning(
      paste0(
        "MICE logged events remain after MICE_EPS=", MICE_EPS,
        ". Inspect the MICE diagnostic sheets in the results workbook."
      )
    )
  } else {
    cat("No MICE logged events after eps fix in outer-fold or final-cohort imputation.\n")
  }

  wb <- openxlsx::createWorkbook()

  openxlsx::addWorksheet(wb, "Class_Distribution")
  openxlsx::writeData(wb, "Class_Distribution", class_table)

  openxlsx::addWorksheet(wb, "Missing_Before")
  openxlsx::writeData(wb, "Missing_Before", missing_before)

  openxlsx::addWorksheet(wb, "MICE_Input_Missing_Before")
  openxlsx::writeData(wb, "MICE_Input_Missing_Before", mice_input_missing_before)

  openxlsx::addWorksheet(wb, "MI_Settings")
  openxlsx::writeData(wb, "MI_Settings", mi_settings_table)

  openxlsx::addWorksheet(wb, "MICE_Input_Variables")
  openxlsx::writeData(wb, "MICE_Input_Variables", mice_input_variables_table)

  openxlsx::addWorksheet(wb, "Derivation_Rules")
  openxlsx::writeData(wb, "Derivation_Rules", derivation_rules_table)

  openxlsx::addWorksheet(wb, "MICE_Log_Summary")
  openxlsx::writeData(wb, "MICE_Log_Summary", mice_log_summary)

  openxlsx::addWorksheet(wb, "MICE_LoggedEvents")
  if (nrow(mice_logged_events_all) > 0) {
    openxlsx::writeData(wb, "MICE_LoggedEvents", mice_logged_events_all)
  } else {
    openxlsx::writeData(
      wb,
      "MICE_LoggedEvents",
      tibble(Status = "No logged events")
    )
  }

  openxlsx::addWorksheet(wb, "Final_MICE_LoggedEvents")
  if (nrow(final_mice_logged_events) > 0) {
    openxlsx::writeData(wb, "Final_MICE_LoggedEvents", final_mice_logged_events)
  } else {
    openxlsx::writeData(
      wb,
      "Final_MICE_LoggedEvents",
      tibble(Status = "No logged events")
    )
  }

  openxlsx::addWorksheet(wb, "Fold_MI_Map")
  openxlsx::writeData(wb, "Fold_MI_Map", foldwise$imputation_map)

  openxlsx::addWorksheet(wb, "Best_Parameters")
  openxlsx::writeData(wb, "Best_Parameters", best_params_table)


  openxlsx::addWorksheet(wb, "Meta_Coefficients")
  openxlsx::writeData(wb, "Meta_Coefficients", meta_coef)

  openxlsx::addWorksheet(wb, "Threshold")
  openxlsx::writeData(wb, "Threshold", threshold_table)

  openxlsx::addWorksheet(wb, "Development_OOF_Metrics")
  openxlsx::writeData(
    wb,
    "Development_OOF_Metrics",
    development_oof_metrics
  )

  openxlsx::addWorksheet(wb, "Base_OOF_Pooled")
  openxlsx::writeData(wb, "Base_OOF_Pooled", base_oof)

  openxlsx::addWorksheet(wb, "SVM_OOF_By_MI")
  openxlsx::writeData(wb, "SVM_OOF_By_MI", svm_oof_raw)

  openxlsx::addWorksheet(wb, "XGB_OOF_By_MI")
  openxlsx::writeData(wb, "XGB_OOF_By_MI", xgb_oof_raw)

  openxlsx::addWorksheet(wb, "Meta_Input")
  openxlsx::writeData(wb, "Meta_Input", meta_df)

  openxlsx::addWorksheet(wb, "Stack_OOF")
  openxlsx::writeData(wb, "Stack_OOF", meta_oof)

  # Export the completed full-cohort datasets used for final fitting.
  # With EXPORT_ALL_MI_DATASETS = FALSE, only the first dataset is written;
  # all imputations and fitted models remain preserved in the RDS bundle.
  n_export_mi <- if (EXPORT_ALL_MI_DATASETS) MICE_M else 1L

  for (j in seq_len(n_export_mi)) {
    imputed_export_j <- bind_cols(
      tibble(
        Row = seq_len(nrow(dev_complete_list[[j]])),
        PDstage = as.character(dev_complete_list[[j]]$PDstage)
      ),
      dev_complete_list[[j]] |> select(all_of(predictor_vars))
    )

    sheet_nm <- sprintf("Final_MI_%02d", j)
    openxlsx::addWorksheet(wb, sheet_nm)
    openxlsx::writeData(wb, sheet_nm, imputed_export_j)

    basic_sheet_nm <- sprintf("Final_Basic_MI_%02d", j)
    openxlsx::addWorksheet(wb, basic_sheet_nm)
    openxlsx::writeData(
      wb,
      basic_sheet_nm,
      bind_cols(
        tibble(Row = seq_len(nrow(dev_basic_complete_list[[j]]))),
        dev_basic_complete_list[[j]]
      )
    )
  }

  openxlsx::saveWorkbook(
    wb,
    file = file.path(MODEL_DIR, "development_model_results.xlsx"),
    overwrite = TRUE
  )

  # Frozen model specification text file
  spec_lines <- c(
    "DEVELOPMENT MODEL SPECIFICATION: MULTIPLE IMPUTATION WITH DERIVED PREDICTORS",
    "============================================",
    paste0("Created: ", Sys.time()),
    paste0("Development N: ", nrow(model_raw)),
    paste0("Predictors: ", paste(predictor_vars, collapse = ", ")),
    "Base learners: SVM RBF + XGBoost",
    "Meta learner: Elastic Net logistic regression",
    paste0(
      "Base OOF probabilities: averaged across ", MICE_M,
      " imputations per patient, then Z-score standardized before meta learner"
    ),
    "Calibration: Platt scaling on stacking OOF probabilities",
    paste0("Frozen Youden threshold: ", signif(final_threshold, 10)),
    "Class imbalance: SMOTE followed by Tomek, training folds only",
    paste0(
      "MICE: method=", MICE_METHOD,
      ", m=", MICE_M,
      ", maxit=", MICE_MAXIT,
      ", eps=", format(MICE_EPS, scientific = TRUE),
      "; outcome excluded from imputation"
    ),
    "MI pooling: mean predicted probability across imputation-specific models",
    paste0("MICE BASIC/source variables: ", paste(imputation_vars, collapse = ", ")),
    paste0("Derived predictors NEVER imputed: ", paste(derived_vars, collapse = ", ")),
    "Derivation rules: AG_ratio=ALB/(TP-ALB); INR=(PT/13.1)^1.31; NPR=NE_C/PLT; PAR=PLT/ALB; TyG=log(1594.26*TG*GLU/2)",
    paste0(
      "eGFR: CR/88.4 to mg/dL; female code=", SEX_FEMALE_CODE,
      ", male code=", SEX_MALE_CODE,
      ", race coefficient=", EGFR_RACE_COEFFICIENT
    ),
    "",
    "SVM best parameters:",
    paste(capture.output(print(svm_best)), collapse = "\n"),
    "",
    "XGBoost best parameters:",
    paste(capture.output(print(xgb_best)), collapse = "\n"),
    "",
    "Elastic Net meta best parameters:",
    paste(capture.output(print(meta_best)), collapse = "\n")
  )

  writeLines(
    spec_lines,
    con = file.path(OUTPUT_DIR, "development_model_specification.txt")
  )

  capture.output(
    sessionInfo(),
    file = file.path(OUTPUT_DIR, "R_SessionInfo.txt")
  )

  cat("\n============================================================\n")
  cat("DEVELOPMENT MODEL TRAINING COMPLETED.\n")
  cat("Frozen bundle:\n")
  cat(
    file.path(MODEL_DIR, "final_stacking_model_bundle.rds"),
    "\n"
  )
  cat("Results workbook:\n")
  cat(
    file.path(MODEL_DIR, "development_model_results.xlsx"),
    "\n"
  )
  cat("============================================================\n")

}, 

  error = function(e) {
  modeling_error <<- e
})


future::plan(future::sequential)

if (!is.null(modeling_error)) {
  stop(modeling_error)
}

# ==============================================================================
# 18. Optional external prediction helper
# ==============================================================================
# This function is defined here for convenience but is NOT run during training.
#
# Locked external prediction logic:
# - no external outcome is required to generate predictions;
# - external rows are ignore=TRUE in MICE and cannot estimate imputation rules;
# - external files provide the same 18 BASIC/source variables used by MICE;
# - exactly bundle$mice_settings$m external completed BASIC datasets are generated
#   when missing source variables require imputation;
# - AG_ratio/eGFR/PAR/NPR/INR/TyG are derived AFTER each external imputation;
# - each completed derived external dataset is paired with the corresponding
#   imputation-specific final SVM/XGBoost fit;
# - SVM and XGBoost probabilities are averaged across imputations FIRST;
# - the pooled base probabilities then enter the frozen meta-learner,
#   Platt calibrator, and frozen threshold.
#
# This matches the development-stage pooling rule used for the base OOF
# probabilities and avoids silently falling back to only the first imputation.
#
# Usage later:
#   bundle <- readRDS(
#     "private/model_objects/final_stacking_model_bundle.rds"
#   )
#   ext_raw <- read_excel("private/data/external_validation_data.xlsx", na = c("", "NA", "N/A"))
#   ext_pred <- predict_external_locked(ext_raw, bundle)
#
predict_external_locked <- function(external_raw, bundle, seed = SEED + 200) {

  required_predictors <- bundle$predictors
  imputation_names <- names(bundle$raw_development_imputation_data)
  m <- bundle$mice_settings$m

  if (is.null(bundle$final_svm_fits) || is.null(bundle$final_xgb_fits)) {
    stop(
      "Bundle does not contain TRUE-MI model lists (final_svm_fits/final_xgb_fits)."
    )
  }

  if (length(bundle$final_svm_fits) != m ||
      length(bundle$final_xgb_fits) != m) {
    stop("Number of fitted base models does not match bundle$mice_settings$m.")
  }

  ext <- as_tibble(external_raw)

  # External deployment requires the SAME 18 BASIC/source variables.
  # Derived predictors are intentionally NOT required from the external file.
  missing_required_basic <- setdiff(imputation_names, names(ext))
  if (length(missing_required_basic) > 0) {
    stop(
      paste0(
        "External data are missing required BASIC/source columns: ",
        paste(missing_required_basic, collapse = ", ")
      )
    )
  }

  ext_imp_input <- ext |>
    select(all_of(imputation_names)) |>
    mutate(
      across(
        everything(),
        ~ suppressWarnings(as.numeric(.x))
      )
    )

  # Validate binary coding in external data where observed.
  for (nm in c("Sex", "Smoke")) {
    vals <- sort(unique(ext_imp_input[[nm]][!is.na(ext_imp_input[[nm]])]))
    if (!all(vals %in% c(0, 1))) {
      stop(paste0("External ", nm, " must be coded as 0/1."))
    }
  }

  needs_imputation <- anyNA(ext_imp_input)

  # Create a list of m completed external BASIC-variable datasets.
  if (!needs_imputation) {

    ext_basic_complete_list <- lapply(
      seq_len(m),
      function(j) ext_imp_input
    )

  } else {

    dev_imp_raw <- bundle$raw_development_imputation_data

    combined <- bind_rows(
      dev_imp_raw,
      ext_imp_input
    )

    # Development rows estimate MICE relations; external rows do not.
    ignore_vec <- c(
      rep(FALSE, nrow(dev_imp_raw)),
      rep(TRUE, nrow(ext_imp_input))
    )

    imp_ext <- mice_impute_predictors(
      predictor_df = combined,
      ignore_vec = ignore_vec,
      seed = seed,
      m = m,
      maxit = bundle$mice_settings$maxit,
      method_name = bundle$mice_settings$method,
      print_flag = FALSE,
      eps = if (!is.null(bundle$mice_settings$eps)) {
        bundle$mice_settings$eps
      } else {
        MICE_EPS
      }
    )

    ext_basic_complete_list <- vector("list", m)

    for (j in seq_len(m)) {
      complete_j <- imp_ext$completed_list[[j]]

      ext_basic_complete_list[[j]] <- as_tibble(
        complete_j[
          (nrow(dev_imp_raw) + 1):nrow(complete_j),
          ,
          drop = FALSE
        ]
      )
    }
  }

  # Derive the six deterministic predictors separately within every completed
  # external BASIC-variable dataset, using the eGFR coding frozen in the bundle.
  frozen_female_code <- if (!is.null(bundle$egfr_settings$female_code)) {
    bundle$egfr_settings$female_code
  } else {
    SEX_FEMALE_CODE
  }
  frozen_male_code <- if (!is.null(bundle$egfr_settings$male_code)) {
    bundle$egfr_settings$male_code
  } else {
    SEX_MALE_CODE
  }
  frozen_race_coefficient <- if (!is.null(bundle$egfr_settings$race_coefficient)) {
    bundle$egfr_settings$race_coefficient
  } else {
    EGFR_RACE_COEFFICIENT
  }

  ext_complete_list <- lapply(
    ext_basic_complete_list,
    function(x) {
      derive_model_predictors(
        x,
        strict = TRUE,
        female_code = frozen_female_code,
        male_code = frozen_male_code,
        race_coefficient = frozen_race_coefficient
      ) |>
        select(all_of(required_predictors))
    }
  )

  if (any(vapply(ext_complete_list, anyNA, logical(1)))) {
    stop("Missing model predictors remain in at least one external MI dataset.")
  }

  # Predict separately with every imputation-specific fitted model.
  svm_prob_list <- vector("list", m)
  xgb_prob_list <- vector("list", m)

  for (j in seq_len(m)) {
    svm_prob_list[[j]] <- predict(
      bundle$final_svm_fits[[j]],
      new_data = ext_complete_list[[j]],
      type = "prob"
    )$.pred_Stage1

    xgb_prob_list[[j]] <- predict(
      bundle$final_xgb_fits[[j]],
      new_data = ext_complete_list[[j]],
      type = "prob"
    )$.pred_Stage1
  }

  svm_prob_mat <- do.call(cbind, svm_prob_list)
  xgb_prob_mat <- do.call(cbind, xgb_prob_list)

  # Locked prediction pooling rule: mean probability across imputations.
  svm_prob <- rowMeans(svm_prob_mat)
  xgb_prob <- rowMeans(xgb_prob_mat)

  svm_mi_sd <- if (m > 1) apply(svm_prob_mat, 1, sd) else rep(0, nrow(ext))
  xgb_mi_sd <- if (m > 1) apply(xgb_prob_mat, 1, sd) else rep(0, nrow(ext))

  meta_new <- tibble(
    SVM_z = (svm_prob - bundle$meta_scaler$SVM_mean) /
      bundle$meta_scaler$SVM_sd,
    XGB_z = (xgb_prob - bundle$meta_scaler$XGB_mean) /
      bundle$meta_scaler$XGB_sd
  )

  stack_raw <- predict(
    bundle$meta_fit,
    new_data = meta_new,
    type = "prob"
  )$.pred_Stage1

  stack_calibrated <- predict(
    bundle$platt_calibrator,
    newdata = data.frame(probs = stack_raw),
    type = "response"
  )

  tibble(
    SVM_probability = svm_prob,
    SVM_MI_SD = svm_mi_sd,
    XGBoost_probability = xgb_prob,
    XGBoost_MI_SD = xgb_mi_sd,
    Stacking_raw_probability = stack_raw,
    Predicted_probability = stack_calibrated,
    Predicted_class = ifelse(
      stack_calibrated >= bundle$final_threshold,
      "Stage1",
      "Stage0"
    )
  )
}
